import type { Metadata } from 'next'

// PROVIDERS
import Providers from '@/providers'
import { NextIntlClientProvider, useMessages } from 'next-intl'

// FONTS
import { Inter, Archivo } from 'next/font/google'

// STYLES
import './globals.css'

const inter = Inter({
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-primary',
})

const archivo = Archivo({
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  variable: '--font-secondary',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: {
    locale: string
  }
}>) {
  const messages = useMessages()
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.variable} ${archivo.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers attribute="class" defaultTheme="dark">
            {children}
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
